# Generated by Django 5.2.2 on 2025-06-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
