# Generated by Django 5.2.2 on 2025-08-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='experience_images/')),
                ('title', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('content', models.JSONField(blank=True, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('experience_date', models.DateField()),
                ('visibility', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('compensation', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('fte', 'fte'), ('internship', 'internship'), ('research', 'research'), ('other', 'other')], max_length=20)),
            ],
        ),
    ]
