# Generated by Django 5.2.2 on 2025-08-28 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
